# -*- coding: utf-8 -*-
"""3_K-means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rrtu3rqbW73UtrYL1SQ_hqI7Myl7f6G-
"""

import numpy as np
import pandas as pd 
import matplotlib.pyplot as mp

X=[[0.1,0.6],[0.15,0.71],[0.08,0.9],[0.16,0.15],[0.2,0.3],[0.25,0.5],[0.24,0.1],[0.3,0.2]]

centres = np.array([[0.1,0.6],[0.3,0.2]])
print ('Initial Centroids : \n',centres)

from sklearn.cluster import KMeans
model= KMeans(n_clusters=2,init=centres,n_init=1)
model.fit(X)
print('Labels:',model.labels_)

#find P6 location
print('P6 belongs to cluster:',model.labels_[5])

#using labels find population around centroids
print('number of population around cluster2:',np.count_nonzero(model.labels_==1))

#find new centroids 
print('New Centroids:',model.cluster_centers_)

